### ISSUE TITLE
Can't use denolib/setup-deno@v2 (v1.x). 404 error

### ISSUE THREAD

**Issue by tomchen** [denolib/setup-deno#79]
I think it was all good hours ago.

It is fine for v1.2, v1.5, nightly. Only v1.x has problem.

Empty repo for testing:
https://github.com/tomchen/github-action-deno-test/runs/1841729178

It shows:

```
Run denolib/setup-deno@v2
  with:
    deno-version: v1.x

Error: Error: Unexpected HTTP response: 404
    at /home/runner/work/_actions/denolib/setup-deno/v2/dist/index.js:3366:25
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/denolib/setup-deno/v2/dist/index.js:3271:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Full raw log:

```
2021-02-05T20:35:48.4245805Z ##[section]Starting: Request a runner to run this job
2021-02-05T20:35:48.5627506Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2021-02-05T20:35:48.5627640Z Can't find any online and idle self-hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2021-02-05T20:35:48.5627886Z Found online and idle hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2021-02-05T20:35:48.6679924Z ##[section]Finishing: Request a runner to run this job
2021-02-05T20:35:54.2997373Z Current runner version: '2.276.1'
2021-02-05T20:35:54.3022416Z ##[group]Operating System
2021-02-05T20:35:54.3023320Z Ubuntu
2021-02-05T20:35:54.3023704Z 18.04.5
2021-02-05T20:35:54.3024118Z LTS
2021-02-05T20:35:54.3024523Z ##[endgroup]
2021-02-05T20:35:54.3025094Z ##[group]Virtual Environment
2021-02-05T20:35:54.3025647Z Environment: ubuntu-18.04
2021-02-05T20:35:54.3026131Z Version: 20210131.1
2021-02-05T20:35:54.3027091Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20210131.1/images/linux/Ubuntu1804-README.md
2021-02-05T20:35:54.3027980Z ##[endgroup]
2021-02-05T20:35:54.3030966Z Prepare workflow directory
2021-02-05T20:35:54.3612921Z Prepare all required actions
2021-02-05T20:35:54.3623328Z Getting action download info
2021-02-05T20:35:54.5922363Z Download action repository 'denolib/setup-deno@v2'
2021-02-05T20:35:56.6538121Z ##[group]Run denolib/setup-deno@v2
2021-02-05T20:35:56.6538741Z with:
2021-02-05T20:35:56.6539227Z   deno-version: v1.x
2021-02-05T20:35:56.6539688Z ##[endgroup]
2021-02-05T20:35:57.5646245Z ##[error]Error: Unexpected HTTP response: 404
    at /home/runner/work/_actions/denolib/setup-deno/v2/dist/index.js:3366:25
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/denolib/setup-deno/v2/dist/index.js:3271:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-02-05T20:35:57.5712652Z Cleaning up orphan processes
```

**Comment by mason-fish** [comment]
I've just started seeing the same, just began today

**Comment by tomchen** [comment]
It's good now.

But I think I saw another problem: my testing repo's configuration yml is almost a copy paste of denolib/setup-deno's basic example https://github.com/denolib/setup-deno#usage , but it fails. OK I'll open another issue and close this one.

**Comment by mason-fish** [comment]
Working for me too now. Seeing as how a new release was just put out right as all this was happening, my guess is that one of the github resources (perhaps https://raw.githubusercontent.com/denoland/deno/master/Releases.md ?) may have been temporarily down, hence the 404.
