### ISSUE TITLE
"basic example" fails?

### ISSUE THREAD

**Issue by tomchen** [denolib/setup-deno#80]
Empty repo for testing:
https://github.com/tomchen/github-action-deno-test/runs/1841938171

https://github.com/tomchen/github-action-deno-test/blob/main/.github/workflows/test.yml
is almost a copy-and-paste of denolib/setup-deno's basic example https://github.com/denolib/setup-deno#usage , but it fails.

```
Check https://deno.land/std/examples/cat.ts
✅ Successfully installed deno_cat
/home/runner/.deno/bin/deno_cat
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    throw new ErrorClass(res.err.message);
          ^
    at processResponse (deno:core/core.js:213:11)
    at Object.jsonOpAsync (deno:core/core.js:230:12)
    at async Object.open (deno:runtime/js/30_files.js:45:17)
    at async https://deno.land/std@0.86.0/examples/cat.ts:4:16
Error: Process completed with exit code 1.
```

**Comment by tomchen** [comment]
My bad. Because that empty repo for testing is set for #79 , I removed `- uses: actions/checkout@v2` and didn't add README.md, so of course it fails here
